### ISSUE TITLE
can't work an js-controler 1.2.7

### ISSUE THREAD

**Issue by dfrozen** [soef/ioBroker.find-my-iphone#16]
host.orangepiplus	2018-03-11 00:05:05.803	error	instance system.adapter.find-my-iphone.0 terminated with code 1 ()
Caught	2018-03-11 00:05:05.803	error	by controller[0]: at startup (bootstrap_node.js:153:9)
Caught	2018-03-11 00:05:05.802	error	by controller[0]: at run (bootstrap_node.js:387:7)
Caught	2018-03-11 00:05:05.802	error	by controller[0]: at Module.runMain (module.js:611:10)
Caught	2018-03-11 00:05:05.801	error	by controller[0]: at Function.Module._load (module.js:445:3)
Caught	2018-03-11 00:05:05.801	error	by controller[0]: at tryModuleLoad (module.js:453:12)
Caught	2018-03-11 00:05:05.800	error	by controller[0]: at Module.load (module.js:494:32)
Caught	2018-03-11 00:05:05.800	error	by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught	2018-03-11 00:05:05.799	error	by controller[0]: at Module._compile (module.js:577:32)
Caught	2018-03-11 00:05:05.799	error	by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:15:20)
Caught	2018-03-11 00:05:05.798	error	by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1320:23)
Caught	2018-03-11 00:05:05.798	error	by controller[0]: TypeError: fns.adapter is not a function
Caught	2018-03-11 00:05:05.797	error	by controller[0]: ^
Caught	2018-03-11 00:05:05.796	error	by controller[0]: fns.adapter = fns.adapter(options);
Caught	2018-03-11 00:05:05.795	error	by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1320
host.orangepiplus	2018-03-11 00:05:02.634	info	instance system.adapter.find-my-iphone.0 started with pid 18378
host.orangepiplus	2018-03-11 00:04:32.611	info	Restart adapter system.adapter.find-my-iphone.0 because enabled

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.find-my-iphone-community#4
