### ISSUE TITLE
Adapter throws exceptions

### ISSUE THREAD

**Issue by jens-maus** [soef/ioBroker.find-my-iphone#2]
After having installed your adapter I configured it with my appleid+password. But as soon as the adapter is started it returns the following error:

```

host.bilbo	2016-11-15 21:27:12.394	info	Restart adapter system.adapter.find-my-iphone.0 because enabled
host.bilbo	2016-11-15 21:27:12.394	error	instance system.adapter.find-my-iphone.0 terminated with code 0 (OK)
find-my-iphone.0	2016-11-15 21:27:12.390	info	terminating
find-my-iphone.0	2016-11-15 21:27:12.389	error	at emitTwo (events.js:87:13)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at Request.self.callback (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/find-my-iphone/node_modules/request/request.js:186:22)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at Request._callback (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/find-my-iphone/index.js:67:12)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at /opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/find-my-iphone/index.js:29:12
find-my-iphone.0	2016-11-15 21:27:12.389	error	at /opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:82:9
find-my-iphone.0	2016-11-15 21:27:12.389	error	at /opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:240:9
find-my-iphone.0	2016-11-15 21:27:12.389	error	at setOurStates (/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:223:5)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at doIt (/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:195:13)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at CDevice.set (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/soef/soef.js:819:24)
find-my-iphone.0	2016-11-15 21:27:12.389	error	at add (/opt/iobroker/node_modules/iobroker.find-my-iphone/node_modules/soef/soef.js:790:21)
find-my-iphone.0	2016-11-15 21:27:12.389	error	TypeError: Cannot set property '_id' of undefined
find-my-iphone.0	2016-11-15 21:27:12.387	error	uncaught exception: Cannot set property '_id' of undefined
find-my-iphone.0	2016-11-15 21:27:09.385	info	starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.find-my-iphone, node: v4.6.2
```

Please note that I have the Two-Factor-Authorization enabled in my AppleID (if this is relevant). In addition, since I enabled the adapter I am receiving automatic email notifications from apple that my appleid was used to login via a web browser to iCloud.

**Comment by jens-maus** [comment]
Problem fixes with 0.0.6. Thanks.
